### ISSUE TITLE
Node Not Found: SubViewport

### ISSUE THREAD

**Issue by LemmaEOF** [Evanator05/Control3D#1]
When I get this imported into a Godot 4.1 project and add it to a scene, it throws up an error reading that `$SubViewport` doesn't exist in the scene. I'm going through the code and it looks like this is pretty critical, but I don't see it in your example screenshot. Is that something I should add or is there a bigger issue at play?

**Comment by Evanator05** [comment]
> When I get this imported into a Godot 4.1 project and add it to a scene, it throws up an error reading that `$SubViewport` doesn't exist in the scene. I'm going through the code and it looks like this is pretty critical, but I don't see it in your example screenshot. Is that something I should add or is there a bigger issue at play?

The SubViewport should be added automatically by the code. When I tested it before uploading it worked fine but that was before Godot 4.1.2 came out. I'll work on a fix for it.

**Comment by LemmaEOF** [comment]
It does seem to work just fine, but it still logs the error. It might be best to save the instanced sub viewport in a script variable?

**Comment by JoelMahon** [comment]
Thanks for fixing this y'all. Just an FYI the version on Godot AssetLib doesn't have this fix, I'm sure it'd save other Godot noobs like me some headaches if you update it there too :).
